"use client";

import { useState } from "react";
import { CheckCircle2, Loader2, Unplug } from "lucide-react";

import { Github } from "@/components/icons";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/context/auth";
import { startGithubConnect } from "@/components/protected/github-connect";

export default function GeneratorGithubPage() {
  const { user, isLoading } = useAuth();
  const [isConnecting, setIsConnecting] = useState(false);
  const [error, setError] = useState("");
  const isConnected = Boolean(user?.github_connected);

  async function handleConnect() {
    setIsConnecting(true);
    setError("");

    try {
      await startGithubConnect();
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Could not start GitHub connection.",
      );
      setIsConnecting(false);
    }
  }

  return (
    <main className="flex h-full min-h-0 overflow-hidden rounded-2xl border border-gray-200 bg-[#FBFBFB] shadow-sm">
      <section className="flex flex-1 flex-col gap-5 overflow-y-auto p-5">
        <div className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">
          <div className="flex flex-col gap-5 md:flex-row md:items-start md:justify-between">
            <div className="min-w-0">
              <div className="flex size-12 items-center justify-center rounded-2xl bg-[#0C5D56]/10 text-[#0C5D56]">
                <Github size={24} />
              </div>
              <h1 className="mt-5 text-2xl font-semibold tracking-normal text-gray-950">
                GitHub publishing
              </h1>
              <p className="mt-2 max-w-2xl text-sm leading-6 text-gray-500">
                Connect GitHub to publish private repositories and manage the
                repository links generated by Anvila.
              </p>
            </div>

            <div
              className={`inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-medium ${
                isConnected
                  ? "border-emerald-200 bg-emerald-50 text-emerald-700"
                  : "border-gray-200 bg-gray-50 text-gray-600"
              }`}
            >
              {isConnected ? <CheckCircle2 size={14} /> : <Unplug size={14} />}
              {isConnected ? "Connected" : "Not connected"}
            </div>
          </div>
        </div>

        <div className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">
          {isLoading ? (
            <div className="flex items-center gap-2 text-sm text-gray-500">
              <Loader2 size={16} className="animate-spin" />
              Checking GitHub connection...
            </div>
          ) : isConnected ? (
            <div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between">
              <div>
                <p className="text-sm font-semibold text-gray-950">
                  @{user?.github_username || "GitHub account"}
                </p>
                <p className="mt-1 text-xs leading-5 text-gray-500">
                  Private publishing is available for this account.
                </p>
              </div>
              <Button
                type="button"
                variant="outline"
                onClick={handleConnect}
                disabled={isConnecting}
                className="self-start"
              >
                {isConnecting ? "Opening..." : "Reconnect GitHub"}
              </Button>
            </div>
          ) : (
            <div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between">
              <div>
                <p className="text-sm font-semibold text-gray-950">
                  Connect your GitHub account
                </p>
                <p className="mt-1 max-w-xl text-xs leading-5 text-gray-500">
                  You can keep using Anvila with email or Google. Connecting
                  GitHub only authorizes repository publishing.
                </p>
              </div>
              <Button
                type="button"
                onClick={handleConnect}
                disabled={isConnecting}
                className="self-start bg-teal-brand text-white hover:bg-[#094a45]"
              >
                {isConnecting ? "Opening..." : "Connect GitHub"}
              </Button>
            </div>
          )}

          {error && (
            <p className="mt-4 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700">
              {error}
            </p>
          )}
        </div>
      </section>
    </main>
  );
}
